### ISSUE TITLE
Merging with brian2tools

### ISSUE THREAD

**Issue by romainbrette** [brian-team/brian2modelfitting#1]
Shouldn't we close brian2modelfitting and merge with brian2tools? (see wiki)

**Comment by thesamovar** [comment]
It's possible that installation of brian2modelfitting might be more complicated than the other things in brian2tools if it uses the GPU as before, so maybe it would be better to keep them separate?

**Comment by mstimberg** [comment]
I think the idea here was to port over the full functionality of the modelfitting toolbox which would justify a full repository of its own I think. In particular because it would be based on code generation and therefore need tests on various architectures and so on while I'd prefer `brian2tools` to stay Python-only.
But then, we could remove this repository until someone is actually working on this...

**Comment by romainbrette** [comment]
I see. Well it was created in 2014 and hasn't changed since then...

I wrote some code for model fitting to traces (not spike trains) that 
has basic functionality. It's a branch of brian2tools (which doesn't 
appear on github so I guess I didn't properly push it). It would be nice 
to be able to use standalone mode but currently not possible (see note 
on brian2tools wiki).

**Comment by mstimberg** [comment]
> I see. Well it was created in 2014 and hasn't changed since then...

Yes, we created a few of these placeholder repositories (same for `brian2hears`) a while ago... Their advantage is that the readme states where to look for the Brian 1 version, but maybe their presence is more confusing than not having them in the first place...

> It's a branch of brian2tools (which doesn't appear on github so I guess I didn't properly push it).

On older versions of PyCharm you had to explicitly tick a checkbox next to the branch name when you wanted to push a new branch -- if you did not do it, it silently did not push anything... Happened to me more than once :-)

**Comment by thesamovar** [comment]
Would it be useful to have a ``brian2wip`` work in progress repository for things like this where we haven't quite worked out how we'll package it and release it etc.?

**Comment by mstimberg** [comment]
Closing this very old issue, for now we have decided to keep `brian2modelfitting` as a separate package.
