### ISSUE TITLE
10 times more samples as requested

### ISSUE THREAD

**Issue by romainbrette** [brian-team/brian2modelfitting#21]
I'm not sure it's a bug or a documentation issue. When I get results with `fitter.results`, I obtain 10 times more values than specified with `TraceFitter(n_samples=...)`.

**Comment by alTeska** [comment]
I run some samples with the newest version of the brian2modelfitting and didn't get the behaviour, can you put a code sample? Is it bound to all formats in `results()`?

**Comment by romainbrette** [comment]
Actually I realize I get in fact number of samples * number of rounds. So that's probably fine, except perhaps this should be mentioned in the docs?
