### ISSUE TITLE
Dynamical coupling

### ISSUE THREAD

**Issue by romainbrette** [brian-team/brian2modelfitting#23]
There's one optimization strategy with highly nonlinear systems which could be interesting to explore. It consists in adding a coupling term k*(V_recording-V_model), which decays over the time of fitting. This could be implemented quite simply by having k as a parameter, and the error criterion is k**2 + a*sum((V_recording-V_model)**2).

At the end we might want to have a second fitting run with k=0 (but starting from the final population?).

**Comment by mstimberg** [comment]
Support for this has been added with #36 (see https://brian2modelfitting.readthedocs.io/en/stable/features/index.html#reference-the-target-values-in-the-equations) – it could need better documentation and an example, though.
