### ISSUE TITLE
Interface with sequential optimization algorithms

### ISSUE THREAD

**Issue by romainbrette** [brian-team/brian2modelfitting#25]
I think it would be useful to interface with sequential optimization algorithms. For example, [lmfit](https://lmfit.github.io/lmfit-py/) has support for parameter bounds. Our choice of using parallelizable algorithms is for performance reasons, but in practice I found that around 100 000 runs are necessary to fit a model to our data. So, it could very well be that using a more standard sequential algorithm requires fewer runs and ends up being more efficient.

I guess it should be possible to make an ask and tell interface for such algorithms. For example, the algorithm (eg lmfit) runs in a separate thread and calls a function f, which informs an ask method, blocks, and unblocks when tell is called.

**Comment by romainbrette** [comment]
I could imagine that we typically start with a population-based algorithm, then refine with a sequential algorithm.

**Comment by mstimberg** [comment]
Closed via #28
