### ISSUE TITLE
Typo in the exception message at the assertion of optimizer's parent class  

### ISSUE THREAD

**Issue by eslam69** [brian-team/brian2modelfitting#41]
https://github.com/brian-team/brian2modelfitting/blob/a6a41e8c97d1683fbccd2be10939bdd739a7dea3/brian2modelfitting/fitter.py#L564
Should it be `"optimizer has to be a child of class Optimizer"` instead?

**Comment by mstimberg** [comment]
>  Should it be `"optimizer has to be a child of class Optimizer"` instead?

Yes indeed, this looks very much like a copy&paste mistake. Thanks – don't hesitate to propose a Pull Request to fix the issue :)
