### ISSUE TITLE
Use more specific exception types

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2modelfitting#7]
[Refers to the current state of PR #2]

Of course a very minor issue, but if possible we should use a more specific exception type than `Exception` (in most places probably `ValueError` and `TypeError`)

https://github.com/brian-team/brian2modelfitting/blob/a4d78d7a952fc8a4ec346b556791d7965d4f80e9/brian2modelfitting/modelfitting/modelfitting.py#L255

**Comment by alTeska** [comment]
I changed a few `Exception` into `ValueError`, but I think the rest is just a matter of a special case. Let me know if there is any other that you spotted.
